name: Build

on:
    push:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - uses: actions/setup-node@v3
              with:
                  node-version: latest

            - run: npm ci

            # - run: npm test

            - run: npm run build

            - run: |
                  git fetch origin builds:builds
                  git checkout builds

            - run: cp -r dist/** .

            - run: |
                  git status
                  git rev-parse main > source_commit
                  git commit -a -m "[GitHub Actions] Updated build" || true
                  git push origin binaries
